#To initinalize in windows env
# python -m venv venv 
# source venv/bin/activate (Not needed after initial setup)
# Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope Process
# .\venv\Scripts\Activate.ps1

site_name: Varastic
extra_css:
  - stylesheets/varastic-theme.css
theme: 
  name: material
  language: en
  features:
  - content.code.annotate
  - content.code.copy
  - content.tabs.link
  - header.autohide 
  - navigation.footer
  - navigation.indexes
  - navigation.sections
  - navigation.tabs
  - navigation.top
  - navigation.highlights
  - navigation.tracking
  - search.share
  - search.highlight
  - search.suggest
  - toc.follow 
  palette: 
  # Palette toggle for dark mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: custom
      accent: custom

    # Palette toggle for light mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      primary: custom
      accent: custom

plugins:
  - search
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: true
      skip_classes:
        - custom-skip-class-name
      auto_caption: false
      caption_position: bottom
      background: white
      shadow: true
      manual: false

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - attr_list
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
  - Home: https://drive.google.com/drive/folders/0AKZm3AsCLVj3Uk9PVA
  - Learning Sections:
    - 'Overview':
      - Purpose: blog_purpose.md
    - 'Blender':
      - 'Architecture': Blender/blender_tips.md
    - 'Foodz':
      - 'Los Angeles': Adventures/Foodz/los_angeles.md
      - 'Washington DC': Adventures/Foodz/washington_dc.md
    - 'Adventures':
      - 'Hiking': Adventures/Hiking/hiking_trails.md

   
      