#To initinalize in windows env
# python -m venv venv 
# source venv/bin/activate 
# Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope Process
# .\venv\Scripts\Activate.ps1

site_name: Varastic
extra_css:
  - stylesheets/varastic-theme.css
theme: 
  name: material
  language: en
  features:
  - content.code.annotate
  - content.code.copy
  - content.tabs.link
  - header.autohide 
  - navigation.footer
  - navigation.indexes
  - navigation.sections
  - navigation.tabs
  - navigation.top
  - navigation.highlights
  - navigation.tracking
  - search.share
  - search.highlight
  - search.suggest
  - toc.follow 
  palette: 
  # Palette toggle for dark mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: custom
      accent: custom

    # Palette toggle for light mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      primary: custom
      accent: custom

plugins:
  - search
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: true
      skip_classes:
        - custom-skip-class-name
      auto_caption: false
      caption_position: bottom
      background: white
      shadow: true
      manual: false

markdown_extentions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - toc:
      permalink: true

nav:
  - Home: https://drive.google.com/drive/folders/0AKZm3AsCLVj3Uk9PVA
  - Learning Sections:
    - 'Overview':
      - Purpose: blog_purpose.md
    - 'Blender':
      - 'Architecture': Blender/blender_tips.md
   
      